/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package worldcupqataralbum;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import data.Album;
import data.Sticker;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author croubs
 */
public class main extends javax.swing.JFrame {

  /**
   * Creates new form main
   */
  public main() {
    initComponents();
    DefaultTableModel dfm = new DefaultTableModel();
    dfm.setRowCount(0);
    this.jTable1.setModel(dfm);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jDReapeated = new javax.swing.JDialog();
    jLabel2 = new javax.swing.JLabel();
    btnYesRepeated = new javax.swing.JButton();
    btnCancelRepeated = new javax.swing.JButton();
    jDAlbum = new javax.swing.JDialog();
    jLabel3 = new javax.swing.JLabel();
    btnYesAlbum = new javax.swing.JButton();
    btnCancelAlbum = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    btnOpenPack = new javax.swing.JButton();
    btnShowAlbum = new javax.swing.JButton();
    btnShowRepeated = new javax.swing.JButton();
    btnDeleteRepeated = new javax.swing.JButton();
    btnRestardAlbum = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();

    jDReapeated.setSize(new java.awt.Dimension(380, 110));

    jLabel2.setText("Are you sure about to delete all your repeated stickers?");

    btnYesRepeated.setText("Confirm");
    btnYesRepeated.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnYesRepeatedActionPerformed(evt);
      }
    });

    btnCancelRepeated.setText("Cancel");
    btnCancelRepeated.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelRepeatedActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jDReapeatedLayout = new javax.swing.GroupLayout(jDReapeated.getContentPane());
    jDReapeated.getContentPane().setLayout(jDReapeatedLayout);
    jDReapeatedLayout.setHorizontalGroup(
      jDReapeatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jDReapeatedLayout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addGroup(jDReapeatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jDReapeatedLayout.createSequentialGroup()
            .addComponent(btnYesRepeated, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
            .addComponent(btnCancelRepeated, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel2))
        .addContainerGap(11, Short.MAX_VALUE))
    );
    jDReapeatedLayout.setVerticalGroup(
      jDReapeatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jDReapeatedLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jDReapeatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnYesRepeated)
          .addComponent(btnCancelRepeated))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jDAlbum.setSize(new java.awt.Dimension(342, 110));

    jLabel3.setText("Are you sure about to delete all your stickers?");

    btnYesAlbum.setText("Confirm");
    btnYesAlbum.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnYesAlbumActionPerformed(evt);
      }
    });

    btnCancelAlbum.setText("Cancel");
    btnCancelAlbum.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelAlbumActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jDAlbumLayout = new javax.swing.GroupLayout(jDAlbum.getContentPane());
    jDAlbum.getContentPane().setLayout(jDAlbumLayout);
    jDAlbumLayout.setHorizontalGroup(
      jDAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jDAlbumLayout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addGroup(jDAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jDAlbumLayout.createSequentialGroup()
            .addComponent(btnYesAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(79, 79, 79)
            .addComponent(btnCancelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel3))
        .addContainerGap(15, Short.MAX_VALUE))
    );
    jDAlbumLayout.setVerticalGroup(
      jDAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jDAlbumLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jDAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnYesAlbum)
          .addComponent(btnCancelAlbum))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("My album");

    jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
    jLabel1.setText("World Cup Qatar 2022 Album");

    btnOpenPack.setText("Open Pack");
    btnOpenPack.setName("btnOpenPack"); // NOI18N
    btnOpenPack.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnOpenPackActionPerformed(evt);
      }
    });

    btnShowAlbum.setText("My Stickers");
    btnShowAlbum.setName("btnShowAlbum"); // NOI18N
    btnShowAlbum.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnShowAlbumActionPerformed(evt);
      }
    });

    btnShowRepeated.setText("Stickers Repeated");
    btnShowRepeated.setName("btnShowRepeated"); // NOI18N
    btnShowRepeated.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnShowRepeatedActionPerformed(evt);
      }
    });

    btnDeleteRepeated.setText("Eliminate Repeated");
    btnDeleteRepeated.setName("btnDeleteRepeated"); // NOI18N
    btnDeleteRepeated.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteRepeatedActionPerformed(evt);
      }
    });

    btnRestardAlbum.setText("Restard Album");
    btnRestardAlbum.setName("btnRestardAlbum"); // NOI18N
    btnRestardAlbum.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRestardAlbumActionPerformed(evt);
      }
    });

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jTable1.setName("jTable1"); // NOI18N
    jScrollPane1.setViewportView(jTable1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addGap(218, 218, 218))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnOpenPack)
            .addGap(18, 18, 18)
            .addComponent(btnShowAlbum)
            .addGap(18, 18, 18)
            .addComponent(btnShowRepeated)
            .addGap(18, 18, 18)
            .addComponent(btnDeleteRepeated)
            .addGap(18, 18, 18)
            .addComponent(btnRestardAlbum)
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(jScrollPane1))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnOpenPack)
          .addComponent(btnShowAlbum)
          .addComponent(btnShowRepeated)
          .addComponent(btnDeleteRepeated)
          .addComponent(btnRestardAlbum))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnOpenPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenPackActionPerformed
    DefaultTableModel dfm = new DefaultTableModel();
    dfm.setColumnIdentifiers(new Object[]{"Code", "Name", "Country", "Repeated"});
    
    try {
      Album a = new Album();
      ArrayList<Sticker> pack = a.openPack();

      pack.forEach((r) -> {
        try {
          if(r.isReapeated()) dfm.addRow(new Object[]{r.code,r.name,r.country,"REPEATED"});
          else dfm.addRow(new Object[]{r.code,r.name,r.country});
        } catch (SQLException ex) {
          Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
      });
    } catch (SQLException ex) {
      Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    this.jTable1.setModel(dfm);
  }//GEN-LAST:event_btnOpenPackActionPerformed

  private void btnShowAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAlbumActionPerformed
    DefaultTableModel dfm = new DefaultTableModel();
    dfm.setColumnIdentifiers(new Object[]{"Code", "Name", "Country"});
    
    try {
      Album a = new Album();
      ArrayList<Album> album = a.showAlbum();

      album.forEach((r) -> {
        dfm.addRow(new Object[]{r.code,r.name,r.country});
      });
    } catch (SQLException ex) {
      Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    this.jTable1.setModel(dfm);
  }//GEN-LAST:event_btnShowAlbumActionPerformed

  private void btnShowRepeatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowRepeatedActionPerformed
    DefaultTableModel dfm = new DefaultTableModel();
    dfm.setColumnIdentifiers(new Object[]{"Code", "Name", "Country", "Amount"});
    
    try {
      Album a = new Album();
      ArrayList<Album> album = a.showRepeated();

      album.forEach((r) -> {
        dfm.addRow(new Object[]{r.code,r.name,r.country,r.amount});
      });
    } catch (SQLException ex) {
      Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    this.jTable1.setModel(dfm);
  }//GEN-LAST:event_btnShowRepeatedActionPerformed

  private void btnDeleteRepeatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRepeatedActionPerformed
    jDReapeated.setVisible(true);
  }//GEN-LAST:event_btnDeleteRepeatedActionPerformed

  private void btnRestardAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestardAlbumActionPerformed
    jDAlbum.setVisible(true);
  }//GEN-LAST:event_btnRestardAlbumActionPerformed

  private void btnYesRepeatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesRepeatedActionPerformed
    try {
      Album a = new Album();      
      a.deleteRepeated();
      
      DefaultTableModel dfm = new DefaultTableModel();
      dfm.setRowCount(0);
      this.jTable1.setModel(dfm);
    } catch (SQLException ex) {
      Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    jDReapeated.setVisible(false);
  }//GEN-LAST:event_btnYesRepeatedActionPerformed

  private void btnCancelRepeatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRepeatedActionPerformed
    jDReapeated.setVisible(false);
  }//GEN-LAST:event_btnCancelRepeatedActionPerformed

  private void btnYesAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesAlbumActionPerformed
    try {
      Album a = new Album();
      a.restartAlbum();
      
      DefaultTableModel dfm = new DefaultTableModel();
      dfm.setRowCount(0);
      this.jTable1.setModel(dfm);
    } catch(SQLException ex) {
      Logger.getLogger(main.class.getName()).log(Level.SEVERE,null,ex);
    }
    
    jDAlbum.setVisible(false);
  }//GEN-LAST:event_btnYesAlbumActionPerformed

  private void btnCancelAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAlbumActionPerformed
    jDAlbum.setVisible(false);
  }//GEN-LAST:event_btnCancelAlbumActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new main().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancelAlbum;
  private javax.swing.JButton btnCancelRepeated;
  private javax.swing.JButton btnDeleteRepeated;
  private javax.swing.JButton btnOpenPack;
  private javax.swing.JButton btnRestardAlbum;
  private javax.swing.JButton btnShowAlbum;
  private javax.swing.JButton btnShowRepeated;
  private javax.swing.JButton btnYesAlbum;
  private javax.swing.JButton btnYesRepeated;
  private javax.swing.JDialog jDAlbum;
  private javax.swing.JDialog jDReapeated;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
